name: Continuous integration

on: [push, pull_request]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        run: ./gradlew test
        
  instrumentedTest:
    name: Instrumented Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Instrumented Tests
        uses: vgaidarji/android-github-actions-emulator@v1.0.1

  apk:
    name: Build APK
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assembleDebug
